# Generated by Django 2.0.5 on 2018-05-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url_name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
            },
        ),
        migrations.AlterModelOptions(
            name='courserecord',
            options={'verbose_name': '上课记录'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户信息表'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': '报名表'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色表', 'verbose_name_plural': '角色表'},
        ),
        migrations.AlterModelOptions(
            name='studyrecord',
            options={'verbose_name': '学习记录'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '账号表', 'verbose_name_plural': '账号表'},
        ),
        migrations.AddField(
            model_name='role',
            name='menu',
            field=models.ManyToManyField(to='crm.Menu'),
        ),
    ]
